### ISSUE TITLE
IPv6 address mangled

### ISSUE THREAD

**Issue by stapelberg** [neko-neko/utmpdump#1]
Thanks for publishing this package!

I did stumble upon an issue, though: printing an utmp record when SSH'ing into my computer via IPv6, I get:

&{Type:7 Pid:1130555 Device:pts/45 Id: User:michael Host:2a02:168:9300:0:6d9:f5ff:fe1f:9de3 Exit:{Termination:0 Exit:0} Session:0 Time:Sun, 27 Oct 2019 11:56:55 CET Addr:22a:6801:93:0:d906:fff5:1ffe:e39d}

You can see that the `Addr` field (parsed by utmpdump) does not match the `Host` field (string).

This is because the `ut_addr_v6` utmp field is stored in Network Byte Order (big endian), but utmpdump is reading the whole utmp file in little endian: https://github.com/neko-neko/utmpdump/blob/e015f7dff491953650ee580c04bb075c94030c25/utmp/utmp.go#L78

(Side note: always using little endian to read utmp seems incorrect—isn’t the file stored in native endianness, i.e. in big endian on big endian architectures?)

A simple fix is to swap the bytes like so:
```go
	first := uint32(0x6801022a)
	swapped := (first&0xFF)<<24 | ((first&0xFF00)>>8)<<16 | ((first&0xFF0000)>>16)<<8 | (first&0xFF000000)>>24
	fmt.Printf("%x:%x\n", (swapped>>16)&0xffff, swapped&0xffff)
```

A cleaner, yet backwards compatibility-breaking fix is to change `Addr [4]int32` into `AddrV6 [16]byte` and return a net.IP from an `Addr()` accessor, like so:

```go
		ip := make(net.IP, 16)
		if err := binary.Read(bytes.NewReader(r.AddrV6[:]), binary.BigEndian, ip); err != nil {
			return err
		}
		if bytes.Equal(ip[4:], net.IPv6zero[4:]) {
			// IPv4 address, shorten the slice so that net.IP behaves correctly:
			ip = ip[:4]
		}
```

I’m not sure whether you’re following Semantic Import Versioning in this package (you should! :), so I have not sent a pull request. Feel free to use the above in a fix, or let me know if you’d prefer a PR.

A more tedious, yet backwards-compatible way to fix this issue would be to retain the Addr field, add the AddrV6 field, add an accessor, and instead of using binary.Read, read each field separately so that we can populate both Addr and AddrV6.

**Comment by neko-neko** [comment]
@stapelberg Sorry too late reply. Hmm, I thought it was only stored in little-endian,
Recognition seems different.
If it's okay, please send PR :)

> I’m not sure whether you’re following Semantic Import Versioning in this package (you should! :)

I'll follow Semantic versioning in this package!

**Comment by stapelberg** [comment]
> I'll follow Semantic versioning in this package!

Just to be clear, are you saying you will follow semantic versioning at a later point (i.e. a breaking fix would be okay), or are you saying you are following semantic versioning right now and would prefer the more elaborate fix that does not break the API?

**Comment by neko-neko** [comment]
@stapelberg I accept a breaking change, I'll follow semantic versioning after the beaking change.

**Comment by stapelberg** [comment]
Okay, thanks. I’ll try to send the PR today or tomorrow.

**Comment by neko-neko** [comment]
@stapelberg Thanks for your PR :) I merged PR and pushed some improvements 👍 
- Added CircleCI
- Added CI status badge
- Added `Contributors` section into README
- Added CHANGELOG.md

Following semantic versioning. 
https://github.com/neko-neko/utmpdump/releases

**Comment by stapelberg** [comment]
Great, thanks!
